name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Deploy subgraph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-alpine-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-node-
        continue-on-error: true
      # issue with github actions, see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - run: npm ci
      - name: authenticate
        run: npm run auth ${{ secrets.ACCESS_TOKEN }}
      - name: Deploy kovan subgraph
        run: ./node_modules/.bin/graph deploy scripts/deploy.js --node https://api.thegraph.com/deploy/ --ipfs https://api.thegraph.com/ipfs/ kwenta/optimism-kovan-main ./subgraphs/main.js
        env:
          NETWORK: optimism-kovan
      - name: Deploy optimism subgraph
        run: ./node_modules/.bin/graph deploy scripts/deploy.js --node https://api.thegraph.com/deploy/ --ipfs https://api.thegraph.com/ipfs/ kwenta/optimism-main ./subgraphs/main.js
        env:
          NETWORK: optimism
